version: '3.9'

services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: a4f9b634862463afa23e2r23QW2R
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - mongodb_data_container:/data/db
    networks:
      - mynetwork
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.runCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mynetwork
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  mynetwork:
volumes:
 mongodb_data_container:
